Add FaunaDo
n400/awesome-faunadb pull request #18
Opened 2024-10-01 13:29 UTC by r-kataria

## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [X] New submissions use the latest Fauna APIs
  - see the [FQL v4 end of life (EOL) announcement](https://docs.fauna.com/fauna/v4/#fql-v4-end-of-life)
- [X] Updated Table of Contents if necessary.
  - Users of VSCode can keep the ToC up to date with the [Markdown All in One](https://github.com/yzhang-gh/vscode-markdown) extension.

### Pull Request Details 📖
https://github.com/r-kataria/FaunaDo

A real-time sync to-do list app built with Next.js, Tailwind CSS, and FaunaDB. Updated to use FQL 10.

2024-10-04 14:27 UTC, ptpaterson requested changes
Thanks for the PR @r-kataria!

We recently removed a lot of old content and it looks like your PR is based on an old commit. Will you please rebase on the lastest changes or otherwise resolve the existing conflicts?

2024-11-21 11:20 UTC, r-kataria commented
Hey! I have rebased on the latest changes. Let me know if there’s anything else you need.

2025-01-18 04:17 UTC, ptpaterson approved these changes

2025-01-18 04:18 UTC, merged

2025-01-18 04:19 UTC, ptpaterson commented
Hi @r-kataria! Very sorry about the delay. Thank you again for your contribution. Happy coding!